---
title: "218_ASSIGNMENT_5_CODE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(remotes)
install_github("yonghah/esri2sf")

library(tidyverse)
library(sf)
library(leaflet)
library(mapboxapi)
library(tigris)
library(jsonlite)
library(esri2sf)
library(readr)
library(tidycensus)
library(censusapi)

Sys.setenv(CENSUS_KEY="67343486046933b2d74f13923ac153228348f817")
census_api_key("67343486046933b2d74f13923ac153228348f817")
```

```{r}
indoor_sensor_block_data_smc <- readRDS("smc_sensors_blocks.rds")
indoor_sensor_cbg_data_smc <- readRDS("smc_sensors_cbgs.rds")

#########
      # fill = race %>% factor(levels = rev(c("Total","White Alone","Black or African American","American Indian and Alaska Native Alone","Asian Alone","Native Hawaiian and Other Pacific Islander Alone","Some Other Race Alone","Two or More Races")))

# Sys.setenv(CENSUS_KEY="67343486046933b2d74f13923ac153228348f817")
# 
# sm_outdoor_weighted <- readRDS("sm_outdoor_weighted.rds")
# 
# smc_places <- places("CA", cb = T) %>%
#   st_centroid() %>%
#   .[counties("CA") %>% filter(NAME == "San Mateo"),] %>%
#   st_drop_geometry() %>%
#   left_join(places("CA", cb = T) %>% select(PLACEFP)) %>%
#   st_as_sf()
# saveRDS(smc_places, "smc_places.rds")
# smc_places <- readRDS("smc_places.rds")

# Jurisdiction Sensor Data
```

```{r}
census_race_categories <- 
  c(
    "White Alone",
    "Black or African American",
    "American Indian and Alaska Native Alone",
    "Asian Alone",
    "Native Hawaiian and Other Pacific Islander Alone",
    "Some Other Race Alone",
    "Two or More Races",
    "Total"
  )

dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

smc_pop_race_2020_block <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )

smc_pop_race_2020_block <- 
  smc_pop_race_2020_block %>% 
  mutate(
    race = case_when(
      category1 == "Population of two or more races:" & is.na(category2) ~ "Two or more races",
      category1 == "Population of two or more races:" ~ "",
      !is.na(category2) ~ category2,
      TRUE ~ ""
    )
  )

smc_pop_race_2020_block <- 
  smc_pop_race_2020_block %>% 
  filter(race != "") %>% 
  select(block, race, pop = estimate)
```

```{r}
smc_pm25_race <-
  (indoor_sensor_block_data_smc %>% st_drop_geometry()) %>% 
  left_join(
    smc_pop_race_2020_block,
    by = c("GEOID10" = "block")
  ) %>% 
  filter(
    !is.na(race)
  ) %>% 
  mutate(
    PM25 = case_when(
    PM25 <= 3.5 ~ "<3.5",
    PM25 <= 4 ~ "3.5-4",
    PM25 <= 4.5 ~ "4-4.5",
    PM25 <= 5 ~ "4.5-5",
    PM25 <= 5.5 ~ "5-5.5",
    TRUE ~ ">5.5"
    )
  ) %>% 
  group_by(race, PM25) %>% 
  summarize(pop = sum(pop, na.rm = T))

smc_pm25_race_stacked <- smc_pm25_race %>% 
  group_by(PM25, race) %>% 
  summarize(pop = sum(pop)) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = PM25 %>% factor(levels = rev(c("<3.5","3.5-4","4-4.5","4.5-5","5-5.5",">5.5"))),
      y = pop,
      fill = race
    ),
    stat = "identity",
    position = "stack"
  ) +
  scale_fill_manual(values = rev(c("#f94144", "#f3722c", "#f9c74f", "#43aa8b", "#33a1fd", "#344CB7", "#7267CB"))) +
  labs(
    x = "PM 2.5",
    y = "Number of households",
    title = "San Mateo County PM2.5 Exposure by Race",
    fill = "Race of householder"
  ) +
  coord_flip()
```
```{r}
saveRDS(smc_pm25_race_stacked, "smc_pm25_race_stacked.rds")
```

```{r, eval=T}
smc_pm25_race_stacked <- readRDS("smc_pm25_race_stacked.rds")
smc_pm25_race_stacked
```

```{r}
smc_race_total <-
  smc_pm25_race %>% 
  group_by(race) %>% 
  summarize(pop = sum(pop)) %>% 
  mutate(PM25 = "Total")

smc_pm25_race_fill <- smc_pm25_race %>% 
  group_by(PM25, race) %>% 
  summarize(pop = sum(pop)) %>% 
  rbind(smc_race_total) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = PM25 %>% factor(levels = rev(c("Total","<3.5","3.5-4","4-4.5","4.5-5","5-5.5",">5.5"))),
      y = pop,
      fill = race
    ),
    stat = "identity",
    position = "fill"
  ) +
  scale_fill_manual(values = rev(c("#f94144", "#f3722c", "#f9c74f", "#43aa8b", "#33a1fd", "#344CB7", "#7267CB"))) +
  labs(
    x = "PM 2.5",
    y = "Proportion of households",
    title = "San Mateo County PM2.5 Exposure by Race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  +
  guides(
    fill = guide_legend(
      reverse = T
    )
  )
```

```{r}
saveRDS(smc_pm25_race_fill, "smc_pm25_race_stacked.rds")
```

```{r, eval=TRUE}
smc_pm25_race_fill <- readRDS("smc_pm25_race_stacked.rds")
smc_pm25_race_fill
```

```{r}
# variable == "B19001_001" ~ "Total",
#         variable == "B19001_002" ~ "Less than $10,000",
#         variable == "B19001_003" ~ "$10,000 to $14,999",
#         variable == "B19001_004" ~ "$15,000 to $19,999",
#         variable == "B19001_005" ~ "$20,000 to $24,999",
#         variable == "B19001_006" ~ "$25,000 to $29,999",
#         variable == "B19001_007" ~ "$30,000 to $34,999",
#         variable == "B19001_008" ~ "$35,000 to $39,999",
#         variable == "B19001_009" ~ "$40,000 to $44,999",
#         variable == "B19001_010" ~ "$45,000 to $49,999",
#         variable == "B19001_011" ~ "$50,000 to $59,999",
#         variable == "B19001_012" ~ "$60,000 to $74,999",
#         variable == "B19001_013" ~ "$75,000 to $99,999",
#         variable == "B19001_014" ~ "$100,000 to $124,999",
#         variable == "B19001_015" ~ "$125,000 to $149,999",
#         variable == "B19001_016" ~ "$150,000 to $199,999",

smc_pop_income_2019_cbg <-
  get_acs(
    year = 2019,
    table = "B19001",
    geography = "block group",
    state = "CA",
    county = "San Mateo"
  ) %>% 
  mutate(
    income = 
      case_when(
        variable == "B19001_001" ~ "Total",
        variable %in% c("B19001_002", "B19001_003","B19001_004","B19001_005","B19001_006") ~ "Less than $30,000",
        variable %in% c("B19001_007","B19001_008","B19001_009","B19001_0010") ~ "$30,000 to 49,999",
        variable %in% c("B19001_011","B19001_012","B19001_013") ~ "$50,000 to 99,999",
        variable %in% c("B19001_014","B19001_015","B19001_016") ~ "$100,000 to 199,999",
        TRUE ~ "$200,000 or more"
      ),
    block_group = GEOID
  ) %>% 
  select(block_group, income, estimate) %>% 
  filter(income != "Total")
```

```{r}
smc_pm25_income <-
  (indoor_sensor_cbg_data_smc %>% st_drop_geometry()) %>% 
  left_join(
    smc_pop_income_2019_cbg,
    by = c("GEOID" = "block_group")
  ) %>% 
  mutate(
    PM25 = case_when(
    PM25 <= 3.5 ~ "<3.5",
    PM25 <= 4 ~ "3.5-4",
    PM25 <= 4.5 ~ "4-4.5",
    PM25 <= 5 ~ "4.5-5",
    PM25 <= 5.5 ~ "5-5.5",
    TRUE ~ ">5.5"
    )
  ) %>% 
  group_by(income, PM25) %>% 
  summarize(estimate = sum(estimate, na.rm = T))

smc_pm25_income_stacked <- 
  smc_pm25_income %>% 
  group_by(PM25, income) %>% 
  summarize(estimate = sum(estimate)) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = PM25 %>% factor(levels = rev(c("<3.5","3.5-4","4-4.5","4.5-5","5-5.5",">5.5"))),
      y = estimate,
      fill = income %>% 
        factor(levels = rev(c("Less than $30,000","$30,000 to 49,999","$50,000 to 99,999","$100,000 to 199,999","$200,000 or more")))
    ),
    stat = "identity",
    position = "stack"
  ) + scale_fill_manual(values = rev(c("#f3722c", "#f9c74f", "#43aa8b", "#33a1fd", "#7267CB"))) +
  labs(
    x = "PM 2.5",
    y = "Number of households",
    title = "San Mateo County PM2.5 Exposure by Household Income",
    fill = "Household Income"
  ) +
  coord_flip()
```

```{r}
saveRDS(smc_pm25_income_stacked, "smc_pm25_income_stacked.rds")
readRDS()
smc_pm25_income_stacked
```

```{r}
smc_income_total <-
  smc_pm25_income %>% 
  group_by(income) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(PM25 = "Total")

smc_pm25_income_fill <- 
  smc_pm25_income %>% 
  filter(income != "Total") %>% 
  group_by(PM25, income) %>% 
  summarize(estimate = sum(estimate)) %>% 
  rbind(smc_income_total) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = PM25 %>% factor(levels = rev(c("Total","<3.5","3.5-4","4-4.5","4.5-5","5-5.5",">5.5"))),
      y = estimate,
      fill = income %>% 
        factor(levels = rev(c("Less than $30,000","$30,000 to 49,999","$50,000 to 99,999","$100,000 to 199,999","$200,000 or more")))
    ),
    stat = "identity",
    position = "fill"
  ) + scale_fill_manual(values = rev(c("","#f3722c", "#f9c74f", "#43aa8b", "#33a1fd", "#7267CB"))) +
  labs(
    x = "PM 2.5",
    y = "Proportion of households",
    title = "San Mateo County PM2.5 Exposure by Household Income",
    fill = "Household Income"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  +
  guides(
    fill = guide_legend(
      reverse = T
    )
  )
```

```{r}
smc_pm25_income_fill
```

```{r}
saveRDS(smc_pm25_income_stacked, "smc_pm25_income_stacked.rds")
```

```{r, eval=T}
smc_pm25_income_stacked <- readRDS("smc_pm25_income_stacked.rds")
smc_pm25_income_stacked
```

```{r}
saveRDS(smc_pm25_income_fill, "smc_pm25_income_fill.rds")
```

```{r, eval=T}
smc_pm25_income_fill <- readRDS("smc_pm25_income_fill.rds")
smc_pm25_income_fill
```

```{r}
outdoor_sensor_data_sm <- readRDS("sm_outdoor_weighted.rds") %>% 
  rbind()
outdoor_sensor_data_epa <- readRDS("epa_sensor_data.rds")
saveRDS(atherthon_sensor_daily, "atherton_sensor_daily.rds")
outdoor_sensor_data_ath <- readRDS("atherton_sensor_daily.rds") 
outdoor_sensor_data_ath <- 
  outdoor_sensor_data_ath %>%
  mutate(
    city = "Atherton"
  )

outdoor_sensor_data_hmb <- readRDS("hmb_sensor_data.rds")
outdoor_sensor_data_hmb <-
  outdoor_sensor_data_hmb %>%
  filter(
    Location != "inside"
  ) %>% 
  mutate(
    city = "Half Moon Bay"
  )

outdoor_sensor_data_rwc <- readRDS("rwc_outdoor_weighted.rds")
outdoor_sensor_data_fc <- readRDS("fc_sensor_data.rds")

outdoor_sensor_data_smc <-
  outdoor_sensor_data_sm %>% 
  bind_rows(
    outdoor_sensor_data_epa,
    outdoor_sensor_data_ath,
    outdoor_sensor_data_hmb,
    outdoor_sensor_data_rwc,
    outdoor_sensor_data_fc
    ) 
```

```{r}
saveRDS(outdoor_sensor_data_smc, "outdoor_sensor_data_smc.rds")
```

```{r, eval=T}
outdoor_sensor_data_smc <- readRDS("outdoor_sensor_data_smc.rds")

smc_outdoor_time_series <- outdoor_sensor_data_smc %>% 
  ggplot() +
  geom_line(
    aes(
      x = date,
      y = PM25,
      color = city
    )
  ) +
  scale_color_manual(values = c("#f94144", "#f3722c", "#f9c74f", "#43aa8b", "#33a1fd", "#344CB7", "#7267CB")) +
  ggtitle("San Mateo County PM 2.5 Time Series")
  
saveRDS(smc_outdoor_time_series, "smc_outdoor_time_series.rds")
```

```{r}
smc_outdoor_time_series <- read_rds("smc_outdoor_time_series.rds")
smc_outdoor_time_series
```


```{r}
saveRDS(smc_pm25_voronoi_cbg, "smc_pm25_voronoi_cbg.rds")
```

