---
title: "Chapter 5 Demo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(mapboxapi)
library(tidycensus)

Sys.setenv(CENSUS_KEY="67343486046933b2d74f13923ac153228348f817")
mb_access_token("pk.eyJ1IjoiYnJpYW5hbWFybyIsImEiOiJja3l1bm1memExcHE1MnF0OHp2ODV6MGN1In0.8fAzGLv5OQahCJuKM6p9vg", install = T, overwrite = TRUE)
library(raster)
```

```{r}
slr <- 25
rp <- 20

path <- paste0("san_mateo_flooding_slr",str_pad(slr, 3, "left", "0"),"/flooding/v2.1/county_san_mateo_flddepth_slr",str_pad(slr, 3, "left", "0"),"_w",str_pad(rp, 3, "left", "0"),".tif")

test_flood <- raster(path)
```

```{r}
sf_boundary <- places("CA") %>% 
  filter(NAME == "San Fransisco")

test_flood_epa <- test_flood %>% 
  crop(
    epa_boundary %>% 
      st_transform(26910) %>% 
      st_bbox()
  )
```

```{r}
epa_cbg <- block_groups("CA","San Mateo", cb = F, progress_bar = F, year = 2019) %>% 
  filter(GEOID == "060816119003") %>% 
  st_transform(4326)

epa_bldgs <- readRDS("epa_bldg.rds") %>% 
  .[___,]

epa_blocks <- 
  # blocks("CA","San Mateo", progress_bar = F, year = 2020) %>% 
  readRDS("epa_blocks.rds") %>% 
  st_transform(4326) %>% 
  .[___,]

acs_vars_2019_5yr <- readRDS("acs_vars_2019_5yr.rds")

epa_blocks_pop <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    GEOID20 = paste0(state,county,tract,block),
    pop = ___
  ) %>% 
  filter(GEOID20 %in% epa_blocks$GEOID20)

smc_bg_vehicle <-
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*",
    regionin = "state:06+county:081",
    vars = "group(B25044)"
  ) %>% 
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>% 
  dplyr::select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      dplyr::select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  dplyr::select(-variable) %>% 
  separate(
    label,
    into = c(____),
    sep = "!!"
  ) %>% 
  filter(!is.na(____)) %>% 
  filter(cbg %in% epa_cbg$GEOID)

smc_bg_vehicle_total <- smc_bg_vehicle %>% 
  filter(vehicles != "___") %>% 
  mutate(
    vehicles = substr(___) %>% as.numeric(),
    vehicle_count = ___ * ___
  ) %>% 
  group_by(___) %>% 
  summarize(___ = sum(___))

epa_block_veh_per_bldg <-
  epa_bldg %>% 
  filter(is.na(___)) %>% # any non-residential buildings?
  select(___) %>% # unique ID for each building
  st_centroid() %>% 
  st_join(___ %>% select(___)) %>% # block shapes
  st_join(___ %>% select(cbg = ___)) %>% # cbg shapes
  st_drop_geometry() %>% 
  group_by(___, ___) %>% # "assuming population is distributed evenly across buildings in a block"
  summarize(bldg_count = ___) %>% # how to get counts?
  left_join(___) %>% # census dataset
  left_join(___) %>% # census dataset
  group_by(___) %>% # "and vehicles are distributed evenly across population"
  mutate(
    veh_per_person = ___/sum(___),
    ppl_per_bldg = ___/___,
    veh_per_bldg = ___*___ # fractional result ok
  )

# dataset with individual buildings, vehicle counts for each building
epa_veh_per_bldg <- epa_bldg %>% 
  filter(is.na(___)) %>% 
  select(___) %>% 
  st_centroid() %>% 
  st_join(___ %>% select(___)) %>% 
  left_join(___ %>% select(___, ___))
```

