---
title: "EquityAnalysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval = F}
cc_hospitals <-
  cc_pois %>% 
  filter(
    amenity == "hospital"
  )

cc_hospital_drive_15min_isochrones <- mb_isochrone(
  cc_hospitals,
  profile = "driving",
  time = 15
)

cc_hospital_drive_15min <-
  cc_hospitals %>% 
  st_drop_geometry() %>% 
  cbind(cc_hospital_drive_15min_isochrones$geometry) %>% 
  st_as_sf()

cc_hospital_drive_5min_isochrones <- mb_isochrone(
  cc_hospitals,
  profile = "driving",
  time = 5
)

cc_hospital_drive_5min <-
  cc_hospitals %>% 
  st_drop_geometry() %>% 
  cbind(cc_hospital_drive_5min_isochrones$geometry) %>% 
  st_as_sf()
```

```{r eval = F}
leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>%
  addPolygons(
    data = cc_hospital_drive_15min,
    label = ~name
  )

leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>%
  addPolygons(
    data = cc_hospital_drive_5min,
    label = ~name
  )
```

```{r eval = F}
san_ram_blocks_2 <- 
  san_ram_blocks %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.))

san_ram_block_hospital_isochrone_intersect_15min <-
  san_ram_blocks_2 %>% 
  st_intersection(
    cc_hospital_drive_15min %>% 
      st_union() %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area
  )

san_ram_block_hospital_isochrone_intersect_5min <-
  san_ram_blocks_2 %>% 
  st_intersection(
    cc_hospital_drive_5min %>% 
      st_union() %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area
  )
```

```{r eval = F}
census_race_categories <- 
  c(
    "White alone",
    "Asian alone",
    "Black or African American alone",
    "Two or More Races",
    "American Indian and Alaska Native alone",
    "Native Hawaiian and Other Pacific Islander alone",
    "Some Other Race alone"
  )

cc_pop_race_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:013",
    vars = "group(P2)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,NA,NA,"race"),
    sep = "!!"
  ) %>% 
  filter(
    !is.na(race)
  ) %>% 
  mutate(
    race = ifelse(
      race %in% census_race_categories,
      ifelse(
        race %in% c("American Indian and Alaska Native alone", "Native Hawaiian and Other Pacific Islander alone"),
        "Some Other Race alone",
        race
      ),
      "Two or More Races"
    )
  )
```

```{r eval = F}
san_ram_race <-
  cc_pop_race_2020 %>% 
  filter(
    block %in% san_ram_blocks$GEOID10
  ) %>% 
  mutate(race = factor(race, levels = unique(cc_pop_race_2020$race))) %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    perc = estimate/sum(estimate),
    group = "San Ramon Full Population"
  ) %>% 
  arrange(
    desc(perc)
  )
  
san_ram_hospital_race_15min <-
  cc_pop_race_2020 %>% 
  mutate(race = factor(race, levels = unique(cc_pop_race_2020$race))) %>% 
  left_join(
    san_ram_block_hospital_isochrone_intersect_15min %>% 
      select(block = GEOID10, perc_area) %>% 
      st_drop_geometry()
  ) %>% 
  filter(!is.na(perc_area)) %>% 
  mutate(
    estimate = estimate * perc_area
  ) %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    estimate = drop_units(estimate),
    perc = estimate/sum(estimate),
    group = "San Ramon Population within \n15 min. drive of hospitals"
  ) %>% 
  arrange(
    desc(perc)
  )

san_ram_hospital_race_5min <-
  cc_pop_race_2020 %>% 
  mutate(race = factor(race, levels = unique(cc_pop_race_2020$race))) %>% 
  left_join(
    san_ram_block_hospital_isochrone_intersect_5min %>% 
      select(block = GEOID10, perc_area) %>% 
      st_drop_geometry()
  ) %>% 
  filter(!is.na(perc_area)) %>% 
  mutate(
    estimate = estimate * perc_area
  ) %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    estimate = drop_units(estimate),
    perc = estimate/sum(estimate),
    group = "San Ramon Population within \n5 min. drive of hospitals"
  ) %>% 
  arrange(
    desc(perc)
  )
```

```{r eval=F}
saveRDS(san_ram_race, "san_ram_race.rds")

saveRDS(san_ram_hospital_race_5min, "san_ram_hospital_race_5min.rds")

saveRDS(san_ram_hospital_race_15min, "san_ram_hospital_race_15min.rds")
```

```{r}
san_ram_race <- readRDS("san_ram_race.rds")

san_ram_hospital_race_5min <- readRDS("san_ram_hospital_race_5min.rds")

san_ram_hospital_race_15min <- readRDS("san_ram_hospital_race_15min.rds")
```

```{r}
rbind(san_ram_race,san_ram_hospital_race_5min) %>% 
  ggplot(
    aes(
      x = "", 
      y = perc, 
      fill = reorder(race,desc(race)) %>% factor(levels = rev(census_race_categories))
    )
  ) + 
  geom_bar(
    stat = "identity", 
    position = position_fill()
  ) +
  geom_text(
    aes(label = paste0(round(perc*100),"%")),
    position = position_fill(vjust = 0.5)
  ) +
  coord_polar(theta = "y") +
  facet_wrap(~ group)  +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  ) + 
  guides(
    fill = guide_legend(nrow=3, byrow=TRUE)
  ) +
  labs(
    fill = "Household\nRace"
  ) + 
  scale_fill_manual(values=c("#FC835D", "#FFDC1F", "#B0CD36","#65BAF3", "#865AF6"))
```

```{r}
rbind(san_ram_race,san_ram_hospital_race_15min) %>% 
  ggplot(
    aes(
      x = "", 
      y = perc, 
      fill = reorder(race,desc(race)) %>% factor(levels = rev(census_race_categories))
    )
  ) + 
  geom_bar(
    stat = "identity", 
    position = position_fill()
  ) +
  geom_text(
    aes(label = paste0(round(perc*100),"%")),
    position = position_fill(vjust = 0.5)
  ) +
  coord_polar(theta = "y") +
  facet_wrap(~ group)  +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  ) + 
  guides(
    fill = guide_legend(nrow=3, byrow=TRUE)
  ) +
  labs(
    fill = "Household\nRace"
  ) + 
  scale_fill_manual(values=c("#FC835D", "#FFDC1F", "#B0CD36","#65BAF3", "#865AF6"))
```

ANTIOCH

```{r eval = F}
ant_blocks_2 <- 
  ant_blocks %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.))

ant_block_hospital_isochrone_intersect_15min <-
  ant_blocks_2 %>% 
  st_intersection(
    cc_hospital_drive_15min %>% 
      st_union() %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area
  )

ant_block_hospital_isochrone_intersect_5min <-
  ant_blocks_2 %>% 
  st_intersection(
    cc_hospital_drive_5min %>% 
      st_union() %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area
  )
```


```{r eval = F}
ant_race <-
  cc_pop_race_2020 %>% 
  filter(
    block %in% ant_blocks$GEOID10
  ) %>% 
  mutate(race = factor(race, levels = unique(cc_pop_race_2020$race))) %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    perc = estimate/sum(estimate),
    group = "Antioch Full Population"
  ) %>% 
  arrange(
    desc(perc)
  )
  
ant_hospital_race_15min <-
  cc_pop_race_2020 %>% 
  mutate(race = factor(race, levels = unique(cc_pop_race_2020$race))) %>% 
  left_join(
    ant_block_hospital_isochrone_intersect_15min %>% 
      select(block = GEOID10, perc_area) %>% 
      st_drop_geometry()
  ) %>% 
  filter(!is.na(perc_area)) %>% 
  mutate(
    estimate = estimate * perc_area
  ) %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    estimate = drop_units(estimate),
    perc = estimate/sum(estimate),
    group = "Antioch Population within \n15 min. drive of hospitals"
  ) %>% 
  arrange(
    desc(perc)
  )

ant_hospital_race_5min <-
  cc_pop_race_2020 %>% 
  mutate(race = factor(race, levels = unique(cc_pop_race_2020$race))) %>% 
  left_join(
    ant_block_hospital_isochrone_intersect_5min %>% 
      select(block = GEOID10, perc_area) %>% 
      st_drop_geometry()
  ) %>% 
  filter(!is.na(perc_area)) %>% 
  mutate(
    estimate = estimate * perc_area
  ) %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    estimate = drop_units(estimate),
    perc = estimate/sum(estimate),
    group = "Antioch Population within \n5 min. drive of hospitals"
  ) %>% 
  arrange(
    desc(perc)
  )
```

```{r eval = F}
saveRDS(ant_race, "ant_race.rds")

saveRDS(ant_hospital_race_5min, "ant_hospital_race_5min.rds")

saveRDS(ant_hospital_race_15min, "ant_hospital_race_15min.rds")
```

```{r}
ant_race <- readRDS("ant_race.rds")

ant_hospital_race_5min <- readRDS("ant_hospital_race_5min.rds")

ant_hospital_race_15min <- readRDS("ant_hospital_race_15min.rds")
```

```{r}
rbind(ant_race, ant_hospital_race_5min) %>% 
  ggplot(
    aes(
      x = "", 
      y = perc, 
      fill = reorder(race,desc(race)) %>% factor(levels = rev(census_race_categories))
    )
  ) + 
  geom_bar(
    stat = "identity", 
    position = position_fill()
  ) +
  geom_text(
    aes(label = paste0(round(perc*100),"%")),
    position = position_fill(vjust = 0.5)
  ) +
  coord_polar(theta = "y") +
  facet_wrap(~ group)  +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  ) + 
  guides(
    fill = guide_legend(nrow=3, byrow=TRUE)
  ) +
  labs(
    fill = "Household\nRace"
  ) + 
  scale_fill_manual(values=c("#FC835D", "#FFDC1F", "#B0CD36","#65BAF3", "#865AF6"))
```

```{r}
rbind(ant_race, ant_hospital_race_15min) %>% 
  ggplot(
    aes(
      x = "", 
      y = perc, 
      fill = reorder(race,desc(race)) %>% factor(levels = rev(census_race_categories))
    )
  ) + 
  geom_bar(
    stat = "identity", 
    position = position_fill()
  ) +
  geom_text(
    aes(label = paste0(round(perc*100),"%")),
    position = position_fill(vjust = 0.5)
  ) +
  coord_polar(theta = "y") +
  facet_wrap(~ group)  +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  ) + 
  guides(
    fill = guide_legend(nrow=3, byrow=TRUE)
  ) +
  labs(
    fill = "Household\nRace"
  ) + 
  scale_fill_manual(values=c("#FC835D", "#FFDC1F", "#B0CD36","#65BAF3", "#865AF6"))
```

