---
title: "a5 demos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
stanford_boundary <- places("CA", cb = T) %>% 
  filter(NAME == "Stanford") %>% 
  st_transform(4326)

stanford_sensors <- bay_sensors_clean %>% 
  .[stanford_boundary,]

start <- "2021-11-28%2000:08:00"
end <- "2021-12-05%2000:08:00"

stanford_sensor_data <- 
  1:nrow(stanford_sensors) %>% 
  map_dfr(function(row){
  
  print(paste0(row,". ",stanford_sensors[row,]$sensor_index))
  
  a1 <- read_csv(paste0(
    "https://api.thingspeak.com/channels/",
    stanford_sensors[row,]$primary_id_a,
    "/feeds.csv?api_key=",
    stanford_sensors[row,]$primary_key_a,
    "&average=1440&round=3&start=",start,
    "&end=", end, 
    "&timezone=America/Los_Angeles"
  ), show_col_types = F) %>% 
    set_names(c("created_at","PM1.0_CF_1_ug/m3_A","PM2.5_CF_1_ug/m3_A","PM10.0_CF_1_ug/m3_A","Uptime_Minutes_A","RSSI_dbm_A","Temperature_F_A","Humidity_%_A","PM2.5_CF_ATM_ug/m3_A"))
      
  a2 <- read_csv(paste0(
    "https://api.thingspeak.com/channels/",
    stanford_sensors[row,]$secondary_id_a,
    "/feeds.csv?api_key=",
    stanford_sensors[row,]$secondary_key_a,
    "&average=1440&round=3&start=",start,
    "&end=", end, 
    "&timezone=America/Los_Angeles"
  ), show_col_types = F) %>% 
    set_names(c("created_at","0.3um/dl_A","0.5um/dl_A","1.0um/dl_A","2.5um/dl_A","5.0um/dl_A","10.0um/dl_A","PM1.0_CF_ATM_ug/m3_A","PM10_CF_ATM_ug/m3_A"))
    
  b1 <- read_csv(paste0(
    "https://api.thingspeak.com/channels/",
    stanford_sensors[row,]$primary_id_b,
    "/feeds.csv?api_key=",
    stanford_sensors[row,]$primary_key_b,
    "&average=1440&round=3&start=",start,
    "&end=", end, 
    "&timezone=America/Los_Angeles"
  ), show_col_types = F) %>% 
    set_names(c("created_at","PM1.0_CF_1_ug/m3_B","PM2.5_CF_1_ug/m3_B","PM10.0_CF_1_ug/m3_B","HEAP_B","ADC0_voltage_B","Atmos_Pres_B","Not_Used_B","PM2.5_CF_ATM_ug/m3_B"))
  
  b2 <- read_csv(paste0(
    "https://api.thingspeak.com/channels/",
    stanford_sensors[row,]$secondary_id_b,
    "/feeds.csv?api_key=",
    stanford_sensors[row,]$secondary_key_b,
    "&average=1440&round=3&start=",start,
    "&end=", end, 
    "&timezone=America/Los_Angeles"
  ), show_col_types = F) %>% 
    set_names(c("created_at","0.3um/dl_B","0.5um/dl_B","1.0um/dl_B","2.5um/dl_B","5.0um/dl_B","10.0um/dl_B","PM1.0_CF_ATM_ug/m3_B","PM10_CF_ATM_ug/m3_B"))
  
  combined <- a1 %>% 
    left_join(a2, by = "created_at") %>% 
    left_join(b1, by = "created_at") %>% 
    left_join(b2, by = "created_at") %>% 
    transmute(
      date = as.Date(created_at),
      ID = as.numeric(stanford_sensors[row,]$sensor_index),
      Location = stanford_sensors[row,]$location_type,
      PM25 = 0.524*as.numeric(`PM2.5_CF_1_ug/m3_A`) - 0.0852*as.numeric(`Humidity_%_A`) + 5.72
    )

}) %>% 
  group_by(date, Location) %>% 
  summarize(
    PM25 = mean(PM25, na.rm = T)
  )
```

