---
title: "building emissions"
output: html_document
---

```{r}
library(tigris)
library(tidyverse)
library(sf)
library(leaflet)
library(mapboxapi)
library(censusapi)
library(tidycensus)
library(lehdr)

# devtools::install_github("jamgreen/lehdr")

Sys.setenv(CENSUS_KEY="67343486046933b2d74f13923ac153228348f817")
census_api_key("67343486046933b2d74f13923ac153228348f817", overwrite = FALSE, install = FALSE)
```

```{r}
pge_elec_emissions_factor <-
  data.frame(
    year = c(2013:2019),
    factor = c(427,435,405,294,210,206,2.68)
  )

pge_elec_emissions_factor %>% 
  ggplot() +
  geom_line(
    aes(
      x = year,
      y = factor
    )
  ) +
  labs(
    x = "Year",
    y = "Pounds of CO2 per MHh",
    title = "PG&E electricity emissions rate"
  )
```

```{r}
pge_data <- 
  2013:2019 %>% 
  map_dfr(function(yr){
    
    factor <- 
      pge_elec_emissions_factor %>% 
      filter(year == yr) %>% 
      pull(factor)
    
    1:4 %>% 
      map_dfr(function(quarter){
        
        c("Electric","Gas") %>% 
          map_dfr(function(type){
            
            filename <- 
              paste0(
                "pge/PGE_",
                yr,
                "_Q",
                quarter,
                "_",
                type,
                "UsageByZip.csv"
              )
            
            temp <- read_csv(filename)
            
            if(yr == 2017 & quarter == 4) {
              temp <- 
                temp %>% 
                filter(MONTH != 9)
            }
            
            print(filename)
            
            temp <-
              temp %>% 
              rename_all(toupper) %>% 
              mutate(
                TOTALKBTU = ifelse(
                  substr(CUSTOMERCLASS,1,1) == "E",
                  TOTALKWH * 3.412,
                  TOTALTHM * 99.976
                ),
                TOTALTCO2E = ifelse(
                  substr(CUSTOMERCLASS,1,1) == "E",
                  TOTALKWH/1000 * factor * 0.000453592,
                  TOTALTHM * 0.00531
                )
              ) %>% 
              select(
                ZIPCODE,
                YEAR,
                MONTH,
                CUSTOMERCLASS,
                TOTALKBTU,
                TOTALTCO2E,
                TOTALCUSTOMERS
              )
            
          })
        
      })
    
  })
```

```{r}
ath_pge_data <-
  pge_data %>% 
  filter(ZIPCODE == 94027) %>% 
  filter(CUSTOMERCLASS %in% c(
    "Elec- Commercial",
    "Elec- Residential",
    "Gas- Commercial",
    "Gas- Residential"
  )) %>% 
  mutate(
    ENERGYTYPE = ifelse(
      CUSTOMERCLASS == "Elec- Commercial",
      "EC",
      ifelse(
        CUSTOMERCLASS == "Elec- Residential",
        "ER",
        ifelse(
          CUSTOMERCLASS == "Gas- Commercial",
          "GC",
          "GR"
          )
        )
      )
    ) %>% 
  group_by(ZIPCODE, ENERGYTYPE, YEAR) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm=T),
    TOTALTCO2E = sum(TOTALTCO2E, na.rm=T), 
    TOTALCUSTOMERS = mean(TOTALCUSTOMERS, na.rm=T),
    CUSTOMERCLASS = CUSTOMERCLASS
  ) %>% 
  group_by(ENERGYTYPE, YEAR, CUSTOMERCLASS) %>%
  summarize(across(
    c(TOTALKBTU,TOTALTCO2E,TOTALCUSTOMERS),
    ~sum(.,na.rm=T)
  ))
```

```{r}
ggplot(
  ath_pge_data, 
  aes(
    x = as.factor(YEAR), 
    y = TOTALKBTU/1000000
  )
) + 
  geom_bar(stat = "identity", aes(fill = ENERGYTYPE), position = "dodge") + 
  labs(x = "Year", y = "GBTU", title = "Atherton Annual Residential and Commercial Energy Usage, 2013 to 2019") + 
  scale_fill_discrete(name="Energy Type",labels = c("Commerical Electricity", "Residential Electricity", "Commercial Gas", "Residential Gas"))
```

```{r}
years <- 2013:2019

atherton_pop <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(atherton_pop) <- c("YEAR", "population")

for (year in years) { 
  temp <- 
    getCensus(
      name = "acs/acs5",
      vintage = year,
      region = "zip code tabulation area:*",
      regionin = "state:06",
      vars = "group(B01001)"
    ) %>% 
    filter(
      zip_code_tabulation_area == 94027
    ) %>% 
    transmute(
      YEAR = year,
      population = B01001_001E
    )
    
  atherton_pop <- rbind(
    atherton_pop, 
    temp
    )
}

ath_pge_pop <-
  ath_pge_data %>% 
  group_by(
   YEAR 
  ) %>% 
  left_join(
    atherton_pop
  ) %>% 
  mutate(
    KBTU_PER_PERSON = TOTALKBTU / population,
    USETYPE = ifelse(ENERGYTYPE %in% c("ER", "GR"), "Residential", "Commercial"),
    ENERGY = ifelse(ENERGYTYPE %in% c("EC", "ER"), "Electricity", "Gas")
  )
```

```{r}
saveRDS(ath_pge_pop, "ath_pge_pop.rds")
ath_pge_pop <- readRDS("ath_pge_pop.rds")
```


```{r}
ath_pge_pop %>%
  ggplot(
    aes(
      x = YEAR,
      y = KBTU_PER_PERSON
    )
  ) + 
  geom_line(
    aes(
      color = USETYPE,
      linetype = ENERGY
    ),
    size = 1
  ) +
  labs(x = "Year", y = "kBTUs per Person", title = "Atherton Annual Energy Use Intensity per Person, 2013 to 2019", color ="Use Type", linetype = "Energy Type") +
  scale_linetype_manual(values = c("solid","dotted"), labels = c("Electricity","Gas"))
```

```{r}
ca_wac_2013to2019 <- NULL

for(year in years) {
  
  filename <- 
    paste0(
      "wac/ca_wac_S000_JT00_",
      year,
      ".csv.gz"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  temp <- temp %>% 
    mutate(
      year = year
    )
  
  ca_wac_2013to2019 <- rbind(ca_wac_2013to2019, temp)

  saveRDS(ca_wac_2013to2019, "ca_wac_2013to2019.rds")
}
```

```{r}
saveRDS(ca_wac_2013to2019, "ca_wac_2013to2019.rds")
ca_wac_2013to2019 <- readRDS("ca_wac_2013to2019.rds");
```

```{r}
san_mateo_blocks <- blocks("CA","San Mateo")

atherton_boundary <- zctas("CA") %>% 
  filter(GEOID10 == "94027")

atherton_blocks <- san_mateo_blocks %>% 
  st_centroid() %>% 
  .[atherton_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(san_mateo_blocks %>% select(GEOID10)) %>% 
  st_as_sf() %>% 
  select(
    GEOID10
  )
```

```{r}
saveRDS(atherton_blocks, "atherton_blocks.rds")
atherton_blocks <- readRDS("atherton_blocks.rds")
```

```{r}
ath_wac_2013to2019 <-
  ca_wac_2013to2019 %>% 
  transmute(
    YEAR = year,
    GEOID10 = w_geocode,
    total_jobs = C000
  ) %>% 
  right_join(
    atherton_blocks
  ) %>% 
  filter(
    !is.na(YEAR)
  ) %>% 
  group_by(
    YEAR
  ) %>% 
  summarize(
    total_jobs = sum(total_jobs)
  )

ath_pge_complete <-
  ath_pge_pop %>% 
  group_by(
   YEAR
  ) %>% 
  left_join(
    ath_wac_2013to2019
  ) %>% 
  mutate(
    KBTU_PER_JOB = TOTALKBTU / total_jobs,
    USETYPE = ifelse(ENERGYTYPE %in% c("ER", "GR"), "Residential", "Commercial"),
    ENERGY = ifelse(ENERGYTYPE %in% c("EC", "ER"), "Electricity", "Gas")
  )
```
```{r}
saveRDS(ath_pge_complete, "ath_pge_complete.rds")
ath_pge_complete <- readRDS("ath_pge_complete.rds")
```

```{r}
ath_pge_complete %>%
  ggplot(
    aes(
      x = YEAR,
      y = KBTU_PER_JOB
    )
  ) + 
  geom_line(
    aes(
      color = USETYPE,
      linetype = ENERGY
    ),
    size = 1
  ) +
  labs(x = "Year", y = "kBTUs per Person", title = "Atherton Annual Energy Use Intensity per Job, 2013 to 2019", color ="Use Type", linetype = "Energy Type") +
  scale_linetype_manual(values = c("solid","dotted"), labels = c("Electricity","Gas"))
```

```{r}
atherton_CDD <- read_csv("atherton_CDD.csv")

atherton_CDD <- 
  atherton_CDD %>% 
  select(
    year,
    `CanESM2 (Average)`
  ) %>% 
  filter(
    year %in% years
  ) %>% 
  rename(
    YEAR = year,
    CDD = `CanESM2 (Average)`
  )

atherton_HDD <- read_csv("atherton_HDD.csv")

atherton_HDD <- 
  atherton_HDD %>% 
  select(
    year,
    `CanESM2 (Average)`
  ) %>% 
  filter(
    year %in% years
  ) %>% 
  rename(
    YEAR = year,
    HDD = `CanESM2 (Average)`
  )
  
ath_pge_complete <-
  ath_pge_complete %>% 
  group_by(
   YEAR
  ) %>% 
  left_join(
    atherton_CDD
  ) %>% 
  left_join(
    atherton_HDD
  ) %>% 
  mutate(
    NORM_KBTU = ifelse(
      ENERGYTYPE == "GR",
      KBTU_PER_PERSON / HDD,
      ifelse(
        ENERGYTYPE == "ER",
        KBTU_PER_PERSON / CDD,
        ifelse(
          ENERGYTYPE == "GC",
          KBTU_PER_JOB / HDD,
          KBTU_PER_PERSON / CDD
        )
      )
    )
  )
```

```{r}
saveRDS(ath_pge_complete, "ath_pge_complete.rds")
ath_pge_complete <- readRDS("ath_pge_complete.rds")
```

```{r}
ath_pge_complete %>%
  ggplot(
    aes(
      x = YEAR,
      y = NORM_KBTU
    )
  ) + 
  geom_line(
    aes(
      color = USETYPE,
      linetype = ENERGY
    ),
    size = 1
  ) +
  labs(x = "Year", y = "kBTUs", title = "Atherton Normalized Annual Energy Use Intensity, 2013 to 2019", color ="Use Type", linetype = "Energy Type") +
  scale_linetype_manual(values = c("solid","dotted"), labels = c("Electricity","Gas"))
```

```{r}
atherton_stats <-
  atherton_pop %>% 
  left_join(
    ath_wac_2013to2019
  ) %>% 
  left_join(
    atherton_CDD
  ) %>% 
  left_join(
    atherton_HDD
  )
```

```{r}
saveRDS(atherton_stats, "atherton_stats.rds")
atherton_stats <- readRDS("atherton_stats.rds")
```


```{r}
# population graph
atherton_stats %>%
  ggplot(
    aes(
      x = YEAR,
      y = population
    )
  ) + 
  geom_line(color = "purple") +
  labs(x = "Year", y = "People", title = "Atherton Population, 2013 to 2019") +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 8000))
```

```{r}
# total jobs graph
atherton_stats %>%
  ggplot(
    aes(
      x = YEAR,
      y = total_jobs
    )
  ) + 
  geom_line(color = "blue") +
  labs(x = "Year", y = "Jobs", title = "Atherton Jobs, 2013 to 2019") +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 3000))
```

```{r}
# total CDD/HDD graph
atherton_stats %>%
  ggplot(
    aes(
      x = YEAR,
      y = total_jobs
    )
  ) + 
  geom_line() +
  labs(x = "Year", y = "Jobs", title = "Atherton Jobs, 2013 to 2019")
```

```{r}
zip_trips_ghg_yearly <- readRDS("zip_trips_ghg_yearly.rds")
```

```{r}
yearly_vehicle_emissions <- 
  zip_trips_ghg_yearly %>% 
  group_by(
    year
  ) %>% 
  summarize(
    ghg = sum(ghg),
  ) %>% 
  mutate(
    type = "vehicle"
  )

yearly_building_emissions <- 
  ath_pge_complete %>% 
  group_by(
    YEAR
  ) %>% 
  summarize(
    ghg = sum(TOTALTCO2E)
  ) %>% 
  rename(
    year = YEAR
  ) %>% 
  mutate(
    type = "building"
  )

atherton_emissions <-
  yearly_building_emissions %>% 
  rbind(
    yearly_vehicle_emissions
  )

saveRDS(atherton_emissions, "atherton_emissions")
```

```{r}
atherton_emissions <- readRDS("atherton_emissions")
```

```{r}
atherton_emissions %>% 
  filter(
    type == "building"
  ) %>% 
  ggplot(
    aes(x=year, y=ghg)
    ) +
  geom_bar(stat="identity",  fill = "#F8766D") + 
  labs(x = "Year", y = "Emissions (metric tons of CO2 Equivalent)", title = "Atherton Total Building Emissions, 2013 to 2019") +
  theme(legend.position = "none")
```

```{r}
atherton_emissions %>% 
  filter(
    type == "vehicle"
  ) %>% 
  ggplot(
    aes(x=year, y=ghg)
    ) +
  geom_bar(stat="identity", fill = "#00BFC4") + 
  labs(x = "Year", y = "Emissions (metric tons of CO2 Equivalent)", title = "Atherton Total Vehicle Emissions, 2013 to 2019") +
  theme(legend.position = "none")
```

```{r}
atherton_emissions %>% 
  ggplot(aes(x=year, y=ghg, group=type)) +
    geom_line(
      aes(color = type)
    ) +
    scale_y_continuous(trans = "log10") +
    labs(x = "Year", y = "log(Emissions in metric tons of CO2e) ()", title = "Atherton Total Building and Vehicle Emissions, 2013 to 2019")
```

