---
title: "vivekvajipey_A6"
output: html_document
---

```{r include=FALSE}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(mapview)

Sys.setenv(CENSUS_KEY="67343486046933b2d74f13923ac153228348f817")

pums_2019_1yr <- getCensus(
  name = "acs/acs1/pums",
  vintage = 2019,
  region = "public use microdata area:*",
  regionin = "state:06",
  vars = c(
    "SERIALNO",
    "SPORDER",
    "PWGTP",
    "WGTP",
    "YBL",
    "BLD",
    "TEN",
    "MV",
    "HINCP",
    "AGEP"
  )
)

saveRDS(pums_2019_1yr, "a6_pums.rds")
pums_2019_1yr <- readRDS("a6_pums.rds")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()
```

```{r}
mapview(sf_pumas)
```


```{r include=FALSE}
sf_pums <- pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)

sf_pums_clean <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)
  ) %>% 
  filter(YBL %in% 1:3) %>% 
  arrange(AGEP) %>% 
  group_by(SERIALNO) %>% 
  summarise_all(first) %>% 
  mutate(
    leadrisk = ifelse(
      HINCP < 90000 & AGEP < 6,
      1,
      0
    )
  ) %>% 
  mutate(
    building = BLD %>% 
      factor(
        levels = sf_pums_clean$BLD %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      ),
    tenure = TEN %>% 
      factor(
        levels = sf_pums_clean$TEN %>% 
          unique() %>% 
          as.numeric() %>% 
          sort()
      ),
    move_recency = MV %>% 
      factor(
        levels = sf_pums_clean$MV %>% 
          unique() %>% 
          as.numeric() %>% 
          sort()
      ),
    puma_code = PUMA %>% 
      factor(
        levels = sf_pums_clean$PUMA %>% 
          unique() %>% 
          sort()
      )
  )
```

```{r include=FALSE}
test <- sf_pums_clean %>% filter(SERIALNO == "2019HU0000927")
```

```{r}
logit_model <- glm(
  leadrisk ~ building + tenure + move_recency + puma_code,
  family = quasibinomial(),
  data = sf_pums_clean
)

summary(logit_model)
```

```{r}
# y-vale: odds
exp(coef(logit_model))

# probability of occurring
exp(coef(logit_model))/(exp(coef(logit_model))+1)
```

```{r}
random_sample <- sample_n(sf_pums_clean, 1)
# SERIALNO = 2019HU0949431, building = 5, tenure = 3, move_recency = 1, puma_code = 07503
```

```{r}
predict(logit_model, random_sample, type = "response")
```
The random sample rents a household (TEN = 3) in a structure with 3 to 4 apartments (BLD = 5), moved in 12 months ago or less (MV = 1), and is located in the South of Market & Potrero PUMA (PUMA = 07503). For these attributes, the logistic model generates a predicted lead risk score of 0.00681127.


```{r include=FALSE}
predicted_score <- 
  predict(logit_model, sf_pums_clean, type = "response")
```

```{r include=FALSE}
sf_pums_clean <- cbind(sf_pums_clean, predicted_score)
```


```{r include=FALSE}
summary_2x2 <-
  sf_pums_clean %>% 
  mutate(
     leadrisk = ifelse(
        leadrisk == 1, 
        "Yes Lead Risk", 
        "No Lead Risk"
    )
  ) %>% 
  pull(leadrisk) %>% 
  table(predicted_score > 0.5)
```

```{r}
summary_2x2
```

